spring:
  datasource:
    username: postgres
    password: root
    url: jdbc:postgresql://localhost:5432/gitlab-ci
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
server:
  port: ${PORT:8080}